### ISSUE TITLE
Failing CircleCi

### ISSUE THREAD

**Issue by mdnaseemashraf** [ayltai/newspaper-android#1]
Failing CircleCI [build](https://circleci.com/gh/ayltai/Newspaper/1722). I wanted to follow your blog tutorial from Medium, [All you need to know about CircleCI 2.0 with Firebase Test Lab](https://medium.com/@ayltai/all-you-need-to-know-about-circleci-2-0-with-firebase-test-lab-2a66785ff3c2). 

Can you update the blog post and setup CircleCI 2.0 again? I'd love to learn how to setup CircleCI 2.0 and Firebase Test Lab since they updated Android SDK to **Android SDK Platform 28**. Thanks.

**Comment by ayltai** [comment]
You don't need to wait for my update to learn how to build successfully.

Check here: https://circleci.com/gh/ayltai/workflows/Newspaper

Pick the ones that were built successfully. For example, https://circleci.com/workflow-run/413d6be9-8723-45fd-8617-3fba857c36c9. Note the commit hash is e62232c. Then checkout the repo at commit https://github.com/ayltai/Newspaper/tree/e62232c1cbba6a5669c0daad28b8cdffe7ffc640.

It doesn't matter which Android SDK version you are using. The CI/CD process is more or less the same.
